linters:
  Indentation:
    width: 4

  PropertySortOrder:
    order:
        - align-content
        - align-items
        - align-self
        - animation
        - animation-delay
        - animation-direction
        - animation-duration
        - animation-iteration-count
        - animation-name
        - animation-play-state
        - animation-timing-function
        - backface-visibility
        - background
        - background-color
        - background-image
        - background-position
        - background-repeat
        - background-size
        - border
        - border-bottom
        - border-bottom-color
        - border-bottom-left-radius
        - border-bottom-right-radius
        - border-bottom-style
        - border-bottom-width
        - border-collapse
        - border-color
        - border-left
        - border-left-color
        - border-left-style
        - border-left-width
        - border-radius
        - border-right
        - border-right-color
        - border-right-style
        - border-right-width
        - border-spacing
        - border-style
        - border-top
        - border-top-color
        - border-top-left-radius
        - border-top-right-radius
        - border-top-style
        - border-top-width
        - border-width
        - bottom
        - box-shadow
        - box-sizing
        - caption-side
        - clear
        - clip
        - color
        - column-count
        - column-fill
        - column-gap
        - column-rule
        - column-span
        - column-width
        - columns
        - content
        - counter-increment
        - counter-reset
        - cursor
        - display
        - empty-cells
        - fill
        - flex
        - flex-basis
        - flex-direction
        - flex-flow
        - flex-grow
        - flex-shrink
        - flex-wrap
        - float
        - font
        - font-effect
        - font-emphasize
        - font-emphasize-position
        - font-emphasize-style
        - font-family
        - font-size
        - font-size-adjust
        - font-stretch
        - font-style
        - font-variant
        - font-weight
        - grid
        - grid-after
        - grid-area
        - grid-auto-columns
        - grid-auto-flow
        - grid-auto-rows
        - grid-before
        - grid-column
        - grid-column-end
        - grid-column-gap
        - grid-column-start
        - grid-columns
        - grid-end
        - grid-gap
        - grid-row
        - grid-row-end
        - grid-row-gap
        - grid-row-start
        - grid-rows
        - grid-start
        - grid-template
        - grid-template-areas
        - grid-template-columns
        - grid-template-rows
        - height
        - hyphens
        - justify-content
        - left
        - letter-spacing
        - line-height
        - list-style
        - list-style
        - list-style-imag
        - list-style-position
        - list-style-type
        - margin
        - margin-bottom
        - margin-left
        - margin-right
        - margin-top
        - max-height
        - max-width
        - min-height
        - min-width
        - nav-down
        - nav-index
        - nav-left
        - nav-right
        - nav-up
        - opacity
        - order
        - outline
        - outline-color
        - outline-offset
        - outline-style
        - outline-width
        - overflow
        - overflow-x
        - overflow-y
        - padding
        - padding-bottom
        - padding-left
        - padding-right
        - padding-top
        - perspective
        - perspective-origin
        - pointer-events
        - position
        - quotes
        - resize
        - right
        - speak
        - src
        - stroke
        - stroke-dasharray
        - stroke-dashoffset
        - stroke-linecap
        - stroke-width
        - tab-size
        - table-layout
        - text-align
        - text-align-last
        - text-decoration
        - text-emphasis
        - text-emphasis-color
        - text-emphasis-position
        - text-emphasis-style
        - text-indent
        - text-justify
        - text-outline
        - text-overflow
        - text-overflow-ellipsis
        - text-overflow-mode
        - text-rendering
        - text-shadow
        - text-transform
        - text-wrap
        - top
        - transform
        - transform-origin
        - transform-style
        - transition
        - transition-delay
        - transition-duration
        - transition-property
        - transition-timing-function
        - user-select
        - vertical-align
        - visibility
        - white-space
        - width
        - word-break
        - word-spacing
        - word-spacing
        - word-wrap
        - z-index
        - zoom
    ColorVariable:
      enabled: false
